# This is a basic workflow to help you get started with Actions

name: Daily Update CI

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a set of commands using the runners shell
      - name: Install
        run: npm install

      # Runs a set of commands using the runners shell
      - name: Generate changes
        run: node ./index.js

      - name: Check changes
        run: npm run test

      # Runs a set of commands using the runners shell
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "daily update"
          add: db/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
